export const AA_MODEL_SELECT_COLUMNS = [
  'id',
  'name',
  'slug',
  'creator_id',
  'creator_name',
  'creator_slug',
  'evaluations',
  'aa_intelligence_index',
  'aa_coding_index',
  'aa_math_index',
  'mmlu_pro',
  'gpqa',
  'hle',
  'livecodebench',
  'scicode',
  'math_500',
  'aime',
  'pricing',
  'price_1m_blended_3_to_1',
  'price_1m_input_tokens',
  'price_1m_output_tokens',
  'median_output_tokens_per_second',
  'median_time_to_first_token_seconds',
  'median_time_to_first_answer_token',
  'first_seen',
  'last_seen',
] as const;
